**1) [P] Create an 52500 x 75 matrix of zeros, stored as X. Then print out the shape of the matrix, the base data
type, the total size of the array in bytes (as an integer), and the total size in megabytes with 3 places of
significance.**

In [1]:
import numpy as np
MEGA = 10**6
ROWS = 52500
COLS = 75
X = np.zeros((ROWS, COLS))
print("The shape of X is {}".format(X.shape))
print("The type of X is {}".format(X.dtype))
print("The total size of X in bytes is {}".format(X.nbytes))
print("The total size of X in MB is {:.3}".format(X.nbytes/MEGA))

The shape of X is (52500, 75)
The type of X is float64
The total size of X in bytes is 31500000
The total size of X in MB is 31.5


**2) [P] Resize X to have the same number of elements, but with 100 rows. Show the shape. Show the number of
bytes (it should be the same as the previous answer)**

In [2]:
X = np.resize(X, (100, ROWS * COLS // 100))
print("The shape of X is {}".format(X.shape))
print("The total size of X in bytes is {}".format(X.nbytes))

The shape of X is (100, 39375)
The total size of X in bytes is 31500000


**3) [P] Redo #1, but use a base datatype of 16-bit integers.**

In [3]:
X = np.zeros((ROWS, COLS), dtype=np.int16)
print("The shape of X is {}".format(X.shape))
print("The type of X is {}".format(X.dtype))
print("The total size of X in bytes is {}".format(X.nbytes))
print("The total size of X in MB is {:.3}".format(X.nbytes/MEGA))

The shape of X is (52500, 75)
The type of X is int16
The total size of X in bytes is 7875000
The total size of X in MB is 7.88


**4) [P] How many dimensions does X have? Answer using the appropriate property of np.ndarray objects.**

In [4]:
print("There are  {} dimensions in X".format(X.ndim))

There are  2 dimensions in X


**5) [P] Enter the following list in your cell:
str_nums = ['2.14', '-9.3', '42']**

**Convert this to a numpy array named X. What is the base type?
Then, convert X to an array of single precision floating point numbers. (HINT: use astype)**

In [5]:
str_nums = ['2.14', '-9.3', '42']
X = np.asarray([float(i) for i in str_nums])
print("The type of X is {}".format(X.dtype))
X = X.astype(np.float32)
print("The type of X is {}".format(X.dtype))

The type of X is float64
The type of X is float32


**6) [P] Create a numpy array called scores, that has scores_1 as the first row and scores_2 as the second
row, using np.concatenate. Then, change days into a np.array from the list days. Verify the shape of
scores and days.**

In [6]:
days = ["Mon","Tue","Wed","Thu","Fri"]
scores_1 = [9.5, 8.75, 8, 10, 7.75]
scores_2 = [9, 8, 10, 8.75, 7.25]

In [7]:
scores = np.concatenate((np.reshape(scores_1, (1,-1)), np.reshape(scores_2, (1,-1))))
days = np.array(days)
print("The shape of scores is {}".format(scores.shape))
print("The shape of days is {}".format(days.shape))
print("scores is given below")
print(scores)

The shape of scores is (2, 5)
The shape of days is (5,)
scores is given below
[[  9.5    8.75   8.    10.     7.75]
 [  9.     8.    10.     8.75   7.25]]


**7) [P] Repeat the previous problem, but repeat it with np.vstack. The array should be identical.**

In [8]:
scores = np.vstack((scores_1, scores_2))
print("The shape of scores is {}".format(scores.shape))
print("scores is given below")
print(scores)

The shape of scores is (2, 5)
scores is given below
[[  9.5    8.75   8.    10.     7.75]
 [  9.     8.    10.     8.75   7.25]]


**8) [M] Compare the result of the expression days == "Fri" if the variable days was a Python list, vs. days
being a numpy array. What is the difference? In general, how does numpy deal with standard comparison
operators?**

In [9]:
days = ["Mon","Tue","Wed","Thu","Fri"]
print("If days is a regular Python list, we get")
print(scores[:, days == "Fri"])
print("vs if days is a numpy array ....")
days = np.array(days)
print(scores[:, days == "Fri"])

If days is a regular Python list, we get
[]
vs if days is a numpy array ....
[[ 7.75]
 [ 7.25]]


The reason for this result is that when we use regular Python lists, days == 'Fri' will just return False, whereas with a numpy array, we will get a list of similar shape consisting of Booleans where each element's Boolean value corresponds to whether the element in the original numpy array was equal to "Fri" or not. For example, in this case we will get [False, False, False, False, True]

**9) [P] Select the scores that fell on Monday**

In [10]:
print(scores[:, days == "Mon"])

[[ 9.5]
 [ 9. ]]


**10) [P] Select all of the scores that are NOT on Monday (Hint – look up the ~ operator)**

In [11]:
print(scores[:, ~(days == "Mon")])

[[  8.75   8.    10.     7.75]
 [  8.    10.     8.75   7.25]]


**11) [P] Select the scores that were on Tuesday or Thursday**

In [12]:
print(scores[:, np.logical_or(days == 'Tue', days == 'Thu')])

[[  8.75  10.  ]
 [  8.     8.75]]


**12) [P] Show the minimum and maximum scores for the entire array of scores**

In [13]:
print("min score was {}".format(np.min(scores)))
print("max score was {}".format(np.max(scores)))

min score was 7.25
max score was 10.0


**13) [P] Show the minimum scores for each week as a new array with the same dimensions**

In [14]:
print(np.amin(scores, axis=1, keepdims=True))

[[ 7.75]
 [ 7.25]]


**14) [P] Report the day that the maximum score occurred each week. (HINT: use argmax and use that result to
index days.)**

In [15]:
print(np.reshape(days[scores.argmax(axis=1)], (-1, 1)))

[['Thu']
 ['Wed']]


**15) [P] Report the mean of the scores of each week**`

In [16]:
mean = np.mean(scores, axis=1).reshape(-1,1)
print(mean)

[[ 8.8]
 [ 8.6]]


**16) [P] Suppose the lowest score was dropped from each week. Report the mean of each week, but without the
minimum score for that week.**

In [17]:
NUM_DAYS = days.shape[0]
mins = np.amin(scores, axis=1, keepdims=True)
new_mean = (mean * NUM_DAYS - mins) / (NUM_DAYS - 1)
print(new_mean)

[[ 9.0625]
 [ 8.9375]]


**17) [P] Convert the scores to fall on a scale from 0-100 instead of 0-10.**

In [18]:
scores = scores / 10 * 100
print(scores)

[[  95.    87.5   80.   100.    77.5]
 [  90.    80.   100.    87.5   72.5]]


**Copy and paste this code into a cell:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X**

In [19]:
np.random.seed(1234)
X = np.random.randint(1,100,50).reshape((10,5))
X

array([[48, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

**18) [P] Select the first row of X**

In [20]:
X[0]

array([48, 84, 39, 54, 77])

**19) [P] Select the last column of X**

In [21]:
X[:,-1]

array([77, 27, 59, 48, 39, 81, 66, 61, 14, 32])

**20) [P] Select the first AND last column of X**

In [22]:
X[:, [0, -1]]

array([[48, 77],
       [25, 27],
       [31, 59],
       [93, 48],
       [51, 39],
       [68, 81],
       [ 4, 66],
       [76, 61],
       [47, 14],
       [97, 32]])

**21) [P] Select every other row of X**

In [23]:
X[::2]

array([[48, 84, 39, 54, 77],
       [31, 44, 31, 27, 59],
       [51, 77, 38, 35, 39],
       [ 4,  3, 20, 13, 66],
       [47, 29, 82, 88, 14]])

**22) [P] Show the transpose of X, but don't change X itself**

In [24]:
np.transpose(X)

array([[48, 25, 31, 93, 51, 68,  4, 76, 47, 97],
       [84, 16, 44, 70, 77, 12,  3, 82, 29, 13],
       [39, 50, 31, 81, 38,  1, 20, 15, 82, 70],
       [54, 24, 27, 74, 35, 76, 13, 72, 88, 96],
       [77, 27, 59, 48, 39, 81, 66, 61, 14, 32]])

**23) [P] Select the first column of X and set the result to Y.**

In [25]:
Y = X[:,0]
Y

array([48, 25, 31, 93, 51, 68,  4, 76, 47, 97])

**24) [P] Increment the first value of Y, then show the corresponding value of X. Did both values in X and Y change?**

In [26]:
Y[0] += 1
X

array([[49, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

Yes the values in both X and Y changed.

**25) [P] Repeat exercise 23, but ensure that Y is assigned a copy of the selected data. Increment the first value of Y
and ensure that the corresponding value of X did not change.**

In [27]:
Y = np.copy(X[:,0])
Y[0] += 1
X

array([[49, 84, 39, 54, 77],
       [25, 16, 50, 24, 27],
       [31, 44, 31, 27, 59],
       [93, 70, 81, 74, 48],
       [51, 77, 38, 35, 39],
       [68, 12,  1, 76, 81],
       [ 4,  3, 20, 13, 66],
       [76, 82, 15, 72, 61],
       [47, 29, 82, 88, 14],
       [97, 13, 70, 96, 32]])

**26) [P] Create an array that contains the sequence of numbers 0, 0.1, 0.2, ... 9.8, 9.9 using arange, as a 10x10
matrix, stored as X.**

In [28]:
X = np.reshape(np.arange(0,10,0.1), (10, 10))
X

array([[ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9],
       [ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9],
       [ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9],
       [ 3. ,  3.1,  3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9],
       [ 4. ,  4.1,  4.2,  4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9],
       [ 5. ,  5.1,  5.2,  5.3,  5.4,  5.5,  5.6,  5.7,  5.8,  5.9],
       [ 6. ,  6.1,  6.2,  6.3,  6.4,  6.5,  6.6,  6.7,  6.8,  6.9],
       [ 7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,  7.7,  7.8,  7.9],
       [ 8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,  8.8,  8.9],
       [ 9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,  9.9]])

**27) [P] Set the RNG seed to 1234. Then create an array X of uniformly distributed data, with all values between 1.0
and 10.0. Then, show the mean, the median, the minimum and maximum values of X.**

In [29]:
seed = 1234
np.random.seed(seed)
X = np.random.rand(10,10) * 10
print("The mean is {}".format(np.mean(X)))
print("The median is {}".format(np.median(X)))
print("The min is {}".format(np.min(X)))
print("The max is {}".format(np.max(X)))

The mean is 5.183629078788024
The median is 5.363649277280128
The min is 0.06208516587129398
The max is 9.920814661883615


**28) [M] Define what is meant by a normal distribution. What are the parameters of a normal distribution?**

The normal distribution is a function which pertains to the probabilistic distribution of variables such that they are symmetrically centered around a certain mean. The two parameters in this distribution are the mean, which serves as the center around which the probabilities are symmetrically distributed, and the standard deviation, which is such that 68% of all variables are situated within 1 standard variable of the mean, while 95% are situated within 2 standard variables.

**29) [M] In simple terms, using a normal distribution, what does the Law of Large Numbers tell us?**

The Law of Large Numbers tells us that if we take an experiment for which we have an expected result, and repeat that experiment a very large number of times (approaching infinity), the mean of the results will approach the expected value, and the distribution of the overall results will resemble that of the normal distribution, with the differences between the two becoming more and more negligible for a larger number of experiments

**30) [P] Write a function called test_normal_dist. The purpose of this function is to evaluate the law of large
numbers. It should have four parameters:**
    
**mu = mean of distribution**

**sd = standard deviation**

**vec_length = length of the vector to generate randomly from a normal distribution, with mu and sd as
parameters**

**num_trials = number of times to repeat the experiment**

In [30]:
def test_normal_dist(vec_length, mu=0, sd=1, num_trials=100):
    seed = 1234
    np.random.seed(seed)
    sum_devs = 0
    for num in range(num_trials):
        current_vec = np.random.normal(loc=mu,scale=sd,size=vec_length)
        sum_devs += abs(mu - np.mean(current_vec))
    return round(sum_devs/num_trials, 4)

**31) [P] Use test_normal_dist to obtain the deviation for vector lengths of 10, 100, 1000, 10000, and 100000. Use a fixed number of trials of 100 for each experiment. Report the results as a numpy array with two
dimensions. the first being the vector length, and the second being the average deviation resulting from your
test_normal_dist function.**

In [31]:
vectors = [10,100,1000,10000,100000]
results = np.array(list(map(test_normal_dist, vectors)), dtype=np.float32)
print(np.stack((vectors, results), axis=-1))

[[  1.00000000e+01   2.38600001e-01]
 [  1.00000000e+02   8.10000002e-02]
 [  1.00000000e+03   2.22999994e-02]
 [  1.00000000e+04   7.89999962e-03]
 [  1.00000000e+05   2.40000011e-03]]
