# Lab 01 - Getting Started
**Class**: *CSCI 349 - Intro to Data Mining*
**Semester**: *2019 SP*
**Name**: *Mateen Qureshi*
**Instructor**: *Brian King*


In [1]:
import sys
print(sys.version)

3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]


**1) [M] Did you read the syllabus? All of it? Do you agree to abide by the cheating rules? Write a sentence clearly indicating your commitment to not cheating.**

I have read the syllabus (yes all of it!). I do not intend to cheat because I feel I would betray my principles and I would hamper my learning.

**2) [M] What are you hoping to get out of this course?**

I think my ideal job or my area of specialization should I go to grad school will involve a healthy bit of data science, and through this course, I wish to be better prepared for that as well as figure out what opportunities lie out there for me.

**3) [P] Print the Python version (available in sys package)**

In [2]:
import sys
print(sys.version)

3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)]


**4) [P] Create a Python list of 10000 random integers in the range 1 to 100, using the random package. Name the
list x_list.**

In [3]:
import random
x_list = [random.randint(1,100) for i in range(10000)]
print(x_list)

[99, 79, 24, 13, 72, 87, 88, 5, 73, 52, 10, 96, 99, 70, 40, 14, 58, 30, 4, 41, 18, 98, 46, 81, 61, 10, 71, 84, 24, 76, 40, 48, 36, 29, 16, 87, 26, 23, 63, 67, 13, 92, 13, 66, 21, 46, 88, 87, 15, 32, 9, 72, 50, 90, 75, 15, 97, 17, 88, 82, 65, 2, 10, 24, 23, 87, 46, 43, 87, 11, 95, 95, 70, 44, 5, 78, 100, 66, 69, 35, 84, 59, 16, 30, 42, 80, 16, 23, 80, 44, 65, 53, 19, 82, 36, 77, 5, 18, 96, 54, 77, 97, 39, 75, 72, 50, 74, 62, 100, 51, 6, 7, 32, 91, 60, 93, 39, 54, 36, 32, 32, 98, 73, 26, 100, 93, 15, 50, 55, 37, 99, 11, 70, 19, 45, 10, 100, 62, 98, 65, 94, 80, 26, 4, 75, 88, 60, 40, 20, 19, 59, 25, 46, 84, 53, 1, 8, 76, 20, 98, 93, 62, 19, 59, 35, 37, 30, 21, 67, 45, 52, 4, 58, 78, 95, 44, 2, 32, 39, 94, 45, 59, 4, 33, 92, 14, 28, 43, 22, 45, 50, 31, 86, 13, 68, 41, 2, 15, 53, 15, 18, 80, 97, 27, 39, 42, 9, 80, 64, 1, 19, 92, 57, 30, 1, 12, 99, 58, 98, 90, 62, 75, 82, 31, 39, 23, 23, 5, 87, 32, 43, 19, 57, 35, 53, 27, 38, 21, 9, 87, 91, 14, 33, 76, 11, 32, 68, 23, 8, 80, 55, 27, 51, 3, 5

**5) [P] What is the minimum value of x_list? What is the max value? What is the mode?**

In [4]:
from collections import defaultdict

min_value = min(x_list)
max_value = max(x_list)
mode = None
print("min value is {}".format(min_value))
print("max value is {}".format(max_value))

tracker = defaultdict(int) 
for i in x_list:
    tracker[i] += 1
    if mode == None:
        mode = i
    else:
        if tracker[i] > tracker[mode]:
            mode = i
print("mode is {}".format(mode))

min value is 1
max value is 100
mode is 99


**6) [P] Write a function to take a list of numbers as a parameter, and return the average of the list. Then, use your
function to report the average value of x_list, printed as a float with 2 places of precision.**

In [5]:
def list_avg(list_of_nums):
    return sum(list_of_nums)/len(list_of_nums)

print(round(list_avg(x_list), 2))

50.38


**7) [P] Create a list called x_hist that represents a histogram, i.e. a distribution of the numerical data, of
x_list. Each entry in x_hist should contain the range of data in widths of 10. So, x_hist[0] represents
the frequency of numbers between 1-10, x_hist[1] is the frequency of numbers between 11-20, and so
on. Be sure to print x_hist at the end.**

In [6]:
INTERVAL_SIZE = 10
num_intervals = max_value // INTERVAL_SIZE
x_hist = [0] * num_intervals
for i in x_list:
    if i % INTERVAL_SIZE == 0:
        x_hist[(i // INTERVAL_SIZE) - 1] += 1
    else:
        x_hist[i//INTERVAL_SIZE] += 1
print(x_hist)

[998, 984, 986, 1043, 1034, 993, 1019, 977, 978, 988]


**8) [M] What is numpy? What are its strengths? Does it have any weaknesses?**

*Sources:* 

*www.numpy.org*

*https://subscription.packtpub.com/book/application_development/9781783985128/3/ch03lvl1sec24/benefits-and-characteristics-of-numpy-arrays
*

Numpy is a Python package which lets us create and manipulate multiple dimensional arrays (can be considered matrices) and has useful functionality and capabilities for processing discrete signals, machine learning, and data mining.

One significant advantage it has over traditional Python arrays is its compactness, where it can store a similar amount of data in only a fraction of the memory, which is great in data mining applications since we usually deal with very large amounts of data. Vector and matrix operations are usually required for data manipulation, and numpy has inbuilt functionality to carry them out efficiently as compared to Python lists.

I can't really think of any disadvantages, as I have been able to achieve most of what I wanted through numpy during my internship and the image processing class where I previously used it. I guess it does take some getting used to if you have not worked with a vector based language like Matlab before. As I mention Matlab, from my experience Matlab is really powerful and while numpy has extensive tools and can integrate with a lot of Python packages.

**9) [P] Import the numpy package as np and print the numpy version**

In [7]:
import numpy as np
#https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-1.php
print(np.__version__)

1.13.3


**10) [M] What is the primary object type in numpy? Can it store data of different types? Discuss.**

NumPy’s main object is a multidimensional array, which must be homogeneous and so it cannot store data of different types: the numbers need to be all of the same type.

**11) [M] Discuss the types of data available in numpy. You need not list every type. Just generalize, and discuss
how the type system is different than the built-in types int and float in Python.**

Numpy makes use of a data type object which describes how the bytes stored within the bounds of an array in memory should be interpreted. The rough equivalent of types int and float would be an array scalar, with the data type object describing whether it is an int or a float, and the number of bytes taken up by the array scalar. In Python, there is really only one type of a particular data class

**12) [P] Create a numpy array from x_list. Reassign it as x_list. Show the contents.**

In [8]:
x_list = np.asarray(x_list)
print(x_list)

[99 79 24 ...,  1 12 38]


**13) [P] Redo the previous exercise, but set the data type of each value to 'float32'**

In [9]:
x_list = np.float32(x_list)
print(x_list)

[ 99.  79.  24. ...,   1.  12.  38.]


**14) [P] Create a length 10 integer array filled with zeros**

In [10]:
new_array = np.zeros(10, dtype=int)
print(new_array)

[0 0 0 0 0 0 0 0 0 0]


**15) [P] Create a float array of 3 rows and 4 columns, all initialized to one.**

In [11]:
float_array = np.ones((3, 4), dtype=float)
print(float_array)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


**16) [P] Create an array of 20 values, evenly spaced between 1 and 3 (HINT – look at np.linspace)**

In [12]:
evenly_spaced = np.linspace(1, 3, num=20, dtype=float)
print(evenly_spaced)

[ 1.          1.10526316  1.21052632  1.31578947  1.42105263  1.52631579
  1.63157895  1.73684211  1.84210526  1.94736842  2.05263158  2.15789474
  2.26315789  2.36842105  2.47368421  2.57894737  2.68421053  2.78947368
  2.89473684  3.        ]


**17) [P] Set the numpy random seed to the value 12345, then create a 10 x 5 array of random integers on the interval [10, 20)**

In [13]:
np.random.seed(12345)
np.random.randint(10, 21, size=(10, 5))

array([[12, 15, 11, 14, 19],
       [15, 12, 11, 16, 11],
       [19, 17, 16, 10, 12],
       [19, 20, 11, 12, 16],
       [17, 17, 17, 18, 17],
       [11, 17, 14, 10, 13],
       [15, 17, 13, 11, 15],
       [12, 15, 13, 18, 15],
       [12, 15, 13, 10, 16],
       [18, 10, 15, 20, 16]])